### ISSUE TITLE
chatGPT 'OPENAI_API_KEY' error

### ISSUE THREAD

**Issue by fenix011** [AleixMT/Linux-Auto-Customizer#119]
Hi there !

when running the chatGPT util  I'm having this issue :

```
File "/home/fenix/.customizer/bin/chatGPT/Content/Python/chatBot/bot.py", line
    openai.api_key = os.environ["OPENAI_API_KEY"]
                     ~~~~~~~~~~^^^^^^^^^^^^^^^^^^
  File "<frozen os>", line 679, in __getitem__
KeyError: 'OPENAI_API_KEY'
```

.. which puzzles me,  as long as i've created and configured an API key for the matter following your useful article in dev.to !
 What am i missing here ?

gracias, gracias, gracias

**Comment by Axlfc** [comment]
Get your openAI API key (Go to [openai webpage](https://beta.openai.com/account/api-keys) to get yours)

Change 'your_API_key_value' to the one you got from openai webpage before running the next command:

<code>echo "OPENAI_API_KEY=your_API_key_value" > ~/.customizer/bin/chatGPT/Content/Python/chatBot/.env</code>

It's the same as creating a new `.env` file in the `/Content/Python/chatBot` repository folder. 

Inside this `.env` file has to have a variable declaration as such:

OPENAI_API_KEY=your_API_key_value 

So the script knows about the OPENAI_API_KEY environment variable when running.
You can find this issue solved in the original repository: https://github.com/Axlfc/UE5-python/issues/1

**Comment by fenix011** [comment]
Uh... ah, typo error from my side !
Wonderful
