### ISSUE TITLE
jupyter; ERROR: The function output_proxy_executioner does not recognize 0 as a valid argument

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#129]
![imagen](https://user-images.githubusercontent.com/14998495/236146202-e5d50563-dee7-4d0f-9ec9-e0b83fc63732.png)

The output_proxy_executioner is located in `jupyterLab.func.sh`:

![imagen](https://user-images.githubusercontent.com/14998495/236151387-662c0e8a-f1ac-4822-9d37-adc5df6019ce.png)

**Comment by Axlfc** [comment]
When I open the application desktop shortcut, this error appears.
![imagen](https://user-images.githubusercontent.com/14998495/236159063-1f3095e8-0bf1-496b-87ac-22d0bff1f883.png)

**Comment by AleixMT** [comment]
1. Describe *issue* to solve
2. Add commits fixing the issue
3. Raise PR
4. Get feedback
5. Return to point 2 if not fixed
6. Merge and close issue
7. Start in point 1 again for a new issue!
