### ISSUE TITLE
prompt || gitprompt; __vte_prompt_command: command not found

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#130]
![imagen](https://user-images.githubusercontent.com/14998495/236150434-54e8dcb1-07bc-473c-bf68-1fe330df3386.png)

**Comment by AleixMT** [comment]
I do not know how to reproduce your issue but I made the installation cleaner

**Comment by AleixMT** [comment]
Closed

**Comment by Axlfc** [comment]
If I make source to the profile using ```function B```, the prompt disappears and I have to launch ```bash```again for the prompt to reload.

_launch_ ```B function```...

![imagen](https://user-images.githubusercontent.com/14998495/236618566-db7192fa-5a5a-4250-8df3-22e8aed54d1d.png)

The solution might be to launch ```bash``` at the end of ```B function```? 
Any further thoughts before closing back this issue?

**Comment by AleixMT** [comment]
You are not showing the issue that you are describing. Where do you use the `B function`?

If the B function is not loading the customizer functions it usually means that your profile files are not loading the rc files. Just debug the code with prints in order to see which files are loaded when you issue the two different fuctions `B` and `b`. 

Also there is the possibility that you have old installations from the customizer that is causing troubles.

**Comment by AleixMT** [comment]
Are customizer function files loaded when issuing `B`?

**Comment by Axlfc** [comment]
> You are not showing the issue that you are describing. Where do you use the B function?

??? The function B clears the terminal. Of course I'm showing the issue I'm describing. I say "_launch B function_" and then I uploaded a screenshot.

> Also there is the possibility that you have old installations from the customizer that is causing troubles.

You know that's not the case, I always test Customizer in new freshly created Virtual Machines. And you know that already.

**Comment by Axlfc** [comment]
> Are customizer function files loaded when issuing `B`?

The initializacions.sh is sourced in the .profile 

But nothing seems to be sourced in .bashrc

**Comment by AleixMT** [comment]
This is not what I asked. 

Can you answer my question?

> Are customizer function files loaded when issuing `B`?

**Comment by AleixMT** [comment]
Closed because of staling
