### ISSUE TITLE
jupyter desktop launcher shows error

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#133]
When double click on desktop shortcut launcher, an error is shown and nor a terminal running server or jupyterLab are not opened.

**Comment by AleixMT** [comment]
Debug the error and raise PR to solve the issue

**Comment by AleixMT** [comment]
Assign yourself to your issues and add the proper tags. I hate having to do it for you.

**Comment by AleixMT** [comment]
Since you are not answering I assume that this feature is orphan and has no maintainer. I will be deleting it.
