### ISSUE TITLE
Feature request: g++ gdb

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#137]
Add installations of g++ & gdb for C++ development.

They are regular apt-get installations.

**Comment by Axlfc** [comment]
![photo_2023-05-06_11-26-29](https://user-images.githubusercontent.com/14998495/236615775-70a8d99a-a870-4d16-990f-c0f8588c98e9.jpg)

WARNING: The current argument g++ is empty or not valid

Installing using gPlusPlus argument does work.

The `g++` argument is invalid, I left it as gPlusPlus (I understand that if g++ was taken as an argument, hardcore changes would have to be made to the core, so I left it as it is)

**Comment by AleixMT** [comment]
Why is this issue labeled "Bug"? You are implementing a feature from scratch, what bug could you be fixing?

**Comment by AleixMT** [comment]
> The `g++` argument is invalid, I left it as gPlusPlus (I understand that if g++ was taken as an argument, hardcore changes would have to be made to the core, so I left it as it is)

Yes, `+` is probably a bash metacharacter so we cannot use them in argument selection. Add the argument `cpp` to select this feature, as `cpp` is the acropnym and file extension for C++

**Comment by AleixMT** [comment]
Since you are not addressing the requested changes I will be deleting this branch
