### ISSUE TITLE
Redo `git-lfs pull` when being sudo and installing the customizer

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Linux-Auto-Customizer#148]
It seems that if you do `git-lfs pull` while being root the files in the `.git` folder are owned by root and then when doing `git checkout` a permission denied error is shown that can be solved using `sudo` when  checking out. This happens when installing the customizer feature as root. Obviously you should not need super privileges to checkout a code in git. 

We must decide if we avoid `git-lfs  pull` when being root or we solve the problem any other way: For example being able to restore the original permissions and owner from the files in `.git` folder after doing the `git-lfs pull` in the `customizer` installation

**Comment by Axlfc** [comment]
#167
