### ISSUE TITLE
no such file or directory on Terminal start

### ISSUE THREAD

**Issue by tikacp** [AleixMT/Linux-Auto-Customizer#15]
After trying this for a bit I wanted to remove it again. However, my terminal complains about

> bash: ~/.customizer/data/functions.sh: No such file or directory

whenever I open a new terminal window. I already looked through the usual .profile .bashrc etc entries, but couldn't find a place where this would still be called.
Any idea how to get rid of this?

**Comment by AleixMT** [comment]
Yes. You may have a line in `/etc/bash.bashrc` (probably the last line) sourcing `~/.customizer/data/functions.sh`. Remove it and you will rid of this. 

Tell me if you achieved to remove that complain and I will close this issue.

Thank you for your issue and sorry for any inconvenience.

**Comment by tikacp** [comment]
Indeed, there it still was. Complaint is gone now. Thanks!
