### ISSUE TITLE
BUG FIX: Collision between wrappers and installation keynames

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Linux-Auto-Customizer#162]
There are some wrappers named the same as a feature keyname.

This makes the customizer behave wrong, because when you want to install for example c, you will be selecting the wrapper and not the feature.

To avoid this, DO NOT use feature keynames as wrapper names or viceversa. Names should be unique. 

I will rename the tags and system categories so there is no collision.

**Comment by AleixMT** [comment]
These installations have been checked for conflicts and are cleaned in the branch:

add anydesk AutoFirma BFunction b bashcolors branch c changebg cheat checkout clean clion clone cmatrix code commit config copyq curl customizer customizerGUI dconfEditor docker dropbox eclipse emojis FFunction f fastcommands fetch ffmpeg firefox gcc ghostwriter gimp git gitcm githubDesktop gitk gitPristine gitprompt calculator terminal tweaks chrome gpaint gparted gradle guake gvim h handbrake hard hardinfo historyoptimization i ideac ideau inkscape ipe ipi ips j k LFunction l loc lolcat megasync mendeley merge mvn nano nemo netTools nmap obsStudio okular onedrive opensshServer p parallel pdfgrep pgadmin pluma postman prompt psql pull push pycharm pycharmpro python3 s screenshots sherlock shortcuts shotwell slack ssh status studio sublime teams telegram templates terminalBackground thunderbird tmux transmission u uget upgrade virtualbox vlc vommit wikit x xclip z zoom

**Comment by Axlfc** [comment]
Created a script to show only the line of the tags of each feature would make easier to identify which installation has wrong tags (remove tags that are name features). Then we can automate to show if the features has the correct tags.

**Comment by Axlfc** [comment]
We can ensure there are no conflicting tags in the branch develop.
