### ISSUE TITLE
chatGPT

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#20]
Get your openAI API key (Go to [openai webpage](https://beta.openai.com/account/api-keys) to get yours)

Change 'your_API_key_value' to the one you got from openai webpage before running the next command:

<code>echo "OPENAI_API_KEY=your_API_key_value" > ~/.customizer/bin/chatGPT/Content/Python/chatBot/.env</code>

<code>bash</code>

**Comment by AleixMT** [comment]
This is already tracked in #19 , I am closing the issue as duplicated
