### ISSUE TITLE
Wiki

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#32]
wiki (web) complex feature descriptions press kit to document Customizer

**Comment by Axlfc** [comment]
We improved the [Home page](https://github.com/AleixMT/Linux-Auto-Customizer/wiki).
Created a new page as [Introduction](https://github.com/AleixMT/Linux-Auto-Customizer/wiki/Introduction).
Updated the [Getting Started page](https://github.com/AleixMT/Linux-Auto-Customizer/wiki/Getting-started) and [Usage page](https://github.com/AleixMT/Linux-Auto-Customizer/wiki/Usage).

**Comment by AleixMT** [comment]
Okay, but why are you removing your assignment? 

Will you finish this issue?

**Comment by AleixMT** [comment]
Since you are not addressing the requested changes and not answering I will be removing the wiki that you copied
