### ISSUE TITLE
Change image cover of github repo

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#33]
Currently the cover photo does not meet the required proportions. 

Resize properly and upload photo

**Comment by Axlfc** [comment]
[based on this](https://github.com/chuckreynolds/social-profile-image-sizes)
## Customizer picture sizes:

### Github Profile Dimensions
* Profile (Identicon) Picture - 500 x 500
* Repo Social Preview image - 1280 × 640

### Gmail (Google Apps)
* Header Logo  - 320 x 132] (png, 35kb or less)

### Youtube Image Dimensions
* Cover Photo - 2560 x 1440
* Video Thumbnail - 1280 x 720 (that's HD yo)

## Twitter Image Dimensions
* Header Image - 1500 x 500
* Profile Photo - 400 x 400
* Post Image - 1024 x 512 (displays inline as 506 x 253)
* Twitter Card: _twitter:card = summary_ - 1:1 (144 x 144 min, 4096 x 4096 max)
* Twitter Card: _twitter:card = summary_large_image_ - 2:1 ratio (300 x 157 min, 4096 x 4096 max)

## PC:
4096x2160
1920x1080
1280x720

## Phone:
1440×2560
1080×1920
720x1280

Files will be hosted in [this repo](https://github.com/Gua-tk/Customizer-logo)

**Comment by AleixMT** [comment]
If I am not looking and telling you exactly what to do you are not able to do anything on your own or what???

**Comment by AleixMT** [comment]
When you are finished raise PR and add the new wallpapers in [this repo ](https://github.com/AleixMT/wallpapers)

**Comment by Axlfc** [comment]
![bars](https://user-images.githubusercontent.com/14998495/221368056-0da67f28-7594-4231-ab5c-35f7dda59d88.png)
![gradient](https://user-images.githubusercontent.com/14998495/221368065-520a06a8-d49d-4f90-a6e1-9a68668aaf58.png)

Custom color codes:

- Black: #000000
- Dark Blue: # 000080
- Navy blue: #3a5a9b
- Light blue: #a3d3f2
- Aquamarine: #00bfff
- Dark Green: #008000
- Green: #00a650
- Yellow: #ffff00
- Dark Yellow: #ffd500
- Orange: #ff8500
- Dark Red: #ff0000
- Red: #d82c20
- Light Grey: #9b9b9b
- Grey: #808080
- White: #ffffff

**Comment by Axlfc** [comment]
Release of the images and wallpapers available in [this link](https://github.com/Gua-tk/Customizer-logo/releases/tag/Images)

**Comment by Axlfc** [comment]
Waiting to get permission in wallpapers repo to make the push but closing the issue as completed @AleixMT

**Comment by AleixMT** [comment]
> Waiting to get permission in wallpapers repo to make the push but closing the issue as completed @AleixMT 

Then, it's not completed and your must not close it xD
