### ISSUE TITLE
Micro-mecenage

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#35]
Wallet ethereum, bitcoin, etc (mecenazco tech buymeacoffee)...

**Comment by Axlfc** [comment]
[Hints here](https://github.com/afaces/afaces.github.io/blob/main/donate.md)

**Comment by AleixMT** [comment]
I will add all the payment and donation links in this commentary:
- Cardano address: addr1v92psazv75ycy3h9kmnpe55swx3f8y027ur42lnzvzaz5cqve45h4
- Cardano QR: ![download](https://user-images.githubusercontent.com/23342150/220339490-64a50d59-f7b1-46e9-b980-d095b4bc64c2.png)
- Ethereum address: 0x23CD3287E100e485B85d8BAE1676ad9068F909a5
- Ethereum QR: ![download (1)](https://user-images.githubusercontent.com/23342150/220340085-6427cc3b-5111-4b2e-a4f7-e59116868398.png)
- Bitcoin address: 342XF1x7wYU9R1VdKhVFAXsBvcYsUdemka
- Bitcoin QR: ![download (2)](https://user-images.githubusercontent.com/23342150/220340345-2fd9854b-1669-44f6-a962-d2b0eb6dae04.png)
- [Buy me a coffee link](https://www.buymeacoffee.com/VidWise)
- Buy me a coffee QR: ![bmc_qr](https://user-images.githubusercontent.com/23342150/220342749-832faa51-9adb-459f-bee1-28e4aee3a90e.png)
- [Stripe link](https://donate.stripe.com/28o15be6H8xlgyQ000)
- Stripe QR: ![qr_28o15be6H8xlgyQ000](https://user-images.githubusercontent.com/23342150/220337258-8dad1721-4dc1-4852-9a64-67705847fa6b.png)

**Comment by AleixMT** [comment]
I am thinking also in adding social media and a link tree. But wwe need to think first how are we going to distribute the data and information and what usage are we going to give to all those services...
