### ISSUE TITLE
Refactor `crontab` manipulation in `changebg` and `tmux` to use an API call

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#38]
Currently the `crontab` configuration is manual and there are already 3 features using a `crontab` call.

Create a new capability to use `crontab` in a feature and refactor features
- [ ] `tmux`
- [ ] `changebg`

**Comment by AleixMT** [comment]
Depends on the closing of issue #42. Until the capability of `crontab` is not  implemented the resolution of this issue is blocked.

**Comment by Axlfc** [comment]
Proposing a function for crontab accepting arguments crontab file; and crontab format and command to be executed
