### ISSUE TITLE
`ssh` welcome message and possible message at the begin of the terminal session

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#39]
Obtain an ASCII art of the customized Tux image or similar and use it for a new feature which will consist in a welcome message in bash terminal

**Comment by Axlfc** [comment]
The message only appears when entering in ssh mode prompt for something neo-fetch or read a random phrase of a list

**Comment by Axlfc** [comment]
We could use `neofetch` for the welcome message. To install `neofetch` we need superuser privileges. Installation command: `sudo apt-get install neofetch`

**Comment by AleixMT** [comment]
Finished!
