### ISSUE TITLE
Capability to add and remove repositories

### ISSUE THREAD

**Issue by Axlfc** [AleixMT/Linux-Auto-Customizer#44]
Currently the capability to add repositories to the package manager is handled using `gpgSignatures`, and `sources`. This is managed on the background using this two variables. `APT_SOURCES_LIST_FOLDER` ans `GPG_TRUSTED_FOLDER`

This has to be managed as a single property that has key names such as downloads which has `downloadKeys`.

Also the logic has to be for any existing package manager.

**Comment by AleixMT** [comment]
Currently the capability to add repository is already implemented using two different properties and is configured only for the `apt` package manager. Only the carbonLang feature is using those capabilities.

I think it is enough with the capavity of this capability. If we need to add complexity we will do it but only when there are features that actually need a more complex capability.
