### ISSUE TITLE
Update npm feature (Node Package Mnager)

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Linux-Auto-Customizer#65]
Update version and also update exec property of the desktop launcher since it is using the argument `-e` of the `gnome-terminal` function, which is deprecated.

**Comment by Axlfc** [comment]
There are several features that has the behaviour to open a new gnome-terminal in its desktop launcher such as:

- [ ] cmatrix
- [ ] clonezilla
- [ ] tmux
- [ ] Python3
- [ ] f-irc
- [ ] julia
- [ ] pacman
- [ ] R
- [ ] wikit
...

**Comment by AleixMT** [comment]
Okay, so the desktop launcher of these features should be using `gnome-terminal -- COMMANDS` instead of `gnome-terminal -e COMMANDS`?
