### ISSUE TITLE
When there is no terminal open and you do "open terminal here" is does not open a terminal in that location (tmux)

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Linux-Auto-Customizer#8]
Probably because tmux is kidnapping the session before the directory changes happens.

When you have a terminal already opened then a new terminal appears and changes the directory to the desired path, while loading tmux too

**Comment by AleixMT** [comment]
It seems that tmux is attaching as many sessions as there are left before seeing that everytghing is attached and then it will throw a new session which will cd inmediately to the place where we wanted to have our terminal in the first place.

**Comment by Axlfc** [comment]
**This is fixed**

**Comment by AleixMT** [comment]
This has been fixed by bypassing the working directory to tmux
