### ISSUE TITLE
Transfer deprecated wrappers to tags properties in the corresponding features

### ISSUE THREAD

**Issue by AleixMT** [AleixMT/Linux-Auto-Customizer#95]
The wrappers that are on `common_data.sh` are deprecated. We need to transfer their data to fields in the tag property of all the corresponding features. **We do not want to keep all the information**, we just want to keep the wrappers that are meaningful and that we will actually use. 

1. **Design** a set of new wrappers that we will apply globally to all features using a property in the tags field. Rememeber that fields in `systemCategories` are also converted to tags. Some ideas:
- [ ] gitFunctions
- [ ] bashFunctions
- [ ] games
- [ ] ...
2. Now run though all the features applying tags and system categories that correspond to them. **Think and design beforehand**

**Comment by AleixMT** [comment]
Meanwhile I will do my part and transfer the wrappers that I actually use, basically iochemroot and iochemuser.

**Comment by AleixMT** [comment]
customDesktop: a add aisleriot alert ant anydesk aspell audacity Autofirma Bfunction b bashcolors branch c caffeine calibre changebg cheat checkout cheese chess clean clementine clion clone clonezilla cmake cmatrix code codeblocks commit config converters copyq curl customizer customizerGUI d dconfEditor dia discord docker drive dropbox Efunction e eclipse emojis Ffunction f fastcommands fdupes fetch ffmpeg filezilla firefox gcc geogebra ghostwritter gimp git gitcm github githubDesktop gitk gitPristine gitprompt calculator mahjongg mines sudoku terminal tweaks go chrome gpàint gparted gradle guake gvim h handbrake hard hardinfo historyoptimization i ideac ideau inkspace ipe ipi ips iqmol j java jupyterLab k keep keyboardFix LFunction l latex libreoffice loc lolcat megasync meld mendeley merge mvn nano nemo netflix netTools nmap nodejs notflix obsStudio octave okular onedrive opensshServer outlook overleaf p parallel pdfgrep pluma postman prompt psql pull push pycharm pycharmpro pypy3 python3 pytorch R remmina rstudio rsync rust s scala scilab screenshots sherlock shortcuts shotcut shotwell skype slack sonarqube sonicPi soundcloud spotify ssh status steam studio sublime synaptic systemFonts teamviewer teams telegram templates terminalBackground thunderbird tmux tor transmission u uget upgrade virtualbox vlc vncviewer vommit wikit wireshark x xclip youtubeDL z zoom

**Comment by AleixMT** [comment]
You can use the tool to apply tags automatically. From #96

**Comment by Axlfc** [comment]
This is a curated list of all the desired tags:

accessibility, administration, automation, backup, collaboration, communication, containerization, database, deployment, documentation, education, email, engineering, environment, files, graphic, hardware, hosting, ide, language, management, math, media, meetings, messaging, modeling, monitor, network, notifications, office, organizing, programming, projectmanagement, publishing, science, scripting, search, security, simulation, social, sound, spreadsheet, sql, system, terminal, text, utility, video, cloudcomputing, mobileapplications, webdevelopment

All other tags different from this ones must be deleted from each feature and if lacking has to be added to avoid shadowing.

**Comment by AleixMT** [comment]
Okay, nice.

I recommend that for this task you implement a spreadsheet (or two: one for the tags wrappers and other for categories wrapper?): tags and systemcategories on rows, features on columns. Intersection is a boolean indicating if a certain feature is included in a certain tag / system category. Preferably CSV stored on the repository.

Did you check if any of these tags is already a systemCategory (or a very related one)? If any, apply it as system category, not a tag. Do not use systemCategories as tags. For example I see the "terminal" tag, which is a system category.

**Comment by AleixMT** [comment]
Also notice that I already included my custom wrapper associated with the tag `customDesktop`, so you must include this tag in your list in order for this tag to not be deleted :+1:

**Comment by AleixMT** [comment]
Also I am missing the tag `games`, `gaming` or something related :dancing_men:

**Comment by AleixMT** [comment]
And what about `gitFunctions` or `bashFunctions`? I am missing them too! You did not include these wrappers in the list... And they have been with us for so many years!

**Comment by Axlfc** [comment]
After removing the tags that are already set as system categories, the list of remaining tags is:

_administration, automation, backup, collaboration, communication, containerization, deployment, environment, hosting, meetings, modeling, notifications, organizing, programming, scripting, search, social, cloudComputing, mobileApplications, customDesktop, gitFunctions, bashFunctions, server, sound, systemMaintenance, cloudStorage, configuration, customization, conversion, hacking, contentManagementSystem, download, compiler_

**Comment by Axlfc** [comment]
List of System Categories:
_AudioVideo, Audio, Video, Development, Education, Game, Graphics, Network, Office, Science, Settings, System, Utility, Building, Debugger, IDE, GUIDesigner, Profiling, RevisionControl, Translation, Calendar, ContactManagement, Database, Dictionary, Chart, Email, Finance, FlowChart, PDA, ProjectManagement, Presentation, Spreadsheet, WordProcessor, 2DGraphics, VectorGraphics, RasterGraphics, 3DGraphics, Scanning, OCR, Photography, Publishing, Viewer, TextTools, DesktopSettings, HardwareSettings, Printing, PackageManager, Dialup, InstantMessaging, Chat, IRCClient, Feed, FileTransfer, HamRadio, News, P2P, RemoteAccess, Telephony, TelephonyTools, VideoConference, WebBrowser, WebDevelopment, Midi, Mixer, Sequencer, Tuner, TV, AudioVideoEditing, Player, Recorder, DiscBurning, ActionGame, AdventureGame, ArcadeGame, BoardGame, BlocksGame, CardGame, KidsGame, LogicGame, RolePlaying, Shooter, Simulation, SportsGame, StrategyGame, Art, Construction, Music, Languages, ArtificialIntelligence, Astronomy, Biology, Chemistry, ComputerScience, DataVisualization, Economy, Electricity, Geography, Geology, Geoscience, History, Humanities, ImageProcessing, Literature, Maps, Math, NumericalAnalysis, MedicalSoftware, Physics, Robotics, Spirituality, Sports, ParallelComputing, Amusement, Archiving, Compression, Electronics, Emulator, Engineering, FileTools, FileManager, TerminalEmulator, Filesystem, Monitor, Security, Accessibility, Calculator, Clock, TextEditor, Documentation, Adult, Core, KDE, GNOME, XFCE, GTK, Qt, Motif, Java, ConsoleOnly, Screensaver, TrayIcon, Applet, Shell_

**Comment by AleixMT** [comment]
gitFunctions and bashFunctions ( #34  )

Also do not include games I made a mistake because we have the system category Game

**Comment by Axlfc** [comment]
This repo has been created: https://github.com/Gua-tk/Customizer-Wrapper-Parsing

It contains the code to generate .csv files with the features names and system categories and tags.

**Comment by AleixMT** [comment]
Now that you have started with the tags, write here what tags you have decided to keep. I told you to do so before filling in the data in case there were missing or spare.

**Comment by Axlfc** [comment]
> Now that you have started with the tags, write here what tags you have decided to keep. I told you to do so before filling in the data in case there were missing or spare.



> After removing the tags that are already set as system categories, the list of remaining tags is:
> 
> _administration, automation, backup, collaboration, communication, containerization, deployment, environment, hosting, meetings, modeling, notifications, organizing, programming, scripting, search, social, cloudComputing, mobileApplications, customDesktop, gitFunctions, bashFunctions, server, sound, systemMaintenance, cloudStorage, configuration, customization, conversion, hacking, contentManagementSystem, download, compiler_

**Comment by AleixMT** [comment]
I need the CSV of the systemcategories ASAP @Axlfc 

Go to branch wrappers_csv and upload it into `data/core/systemcategories.csv`

**Comment by Axlfc** [comment]
You got it

**Comment by Axlfc** [comment]
> I need the CSV of the systemcategories ASAP @Axlfc
> 
> Go to branch wrappers_csv and upload it into `data/core/systemcategories.csv`

You got it now

**Comment by AleixMT** [comment]
I consider this done. 

If we need new wrappers we just need to modify the CSV.

Same with the desktop categories. 

CSV of the system categories could use some completion but I won't fix it.
